language: go

go:
- 1.12.x

env:
  - GO111MODULE=on

install: true # skips default installation step

before_script:
  - export VERSION=${TRAVIS_BRANCH}  BUILDNUM=${TRAVIS_BUILD_NUMBER}
script:
  - docker-compose -f docker-compose.test.yml up --abort-on-container-exit --build unit-test
  - docker-compose -f docker-compose.test.yml up --abort-on-container-exit --build integration-test

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
  - provider: script
    script: docker push linksmart/sc:latest
    on:
      branch: master
  - provider: script
    script: docker tag linksmart/sc linksmart/sc:${TRAVIS_TAG} &&
      docker push linksmart/sc:${TRAVIS_TAG}
    on:
      tags: true
  - provider: script
    script: export NAME=service-catalog LDFLAGS="-X main.Version=$version -X main.BuildNumber=$buildnum" &&
      curl -s https://raw.githubusercontent.com/linksmart/ci-scripts/master/go/go-build.sh | bash
    on:
      branch: master

