language: go

go:
  - 1.12.x

script:
  - docker-compose -f docker-compose.test.yml up --abort-on-container-exit --build unit-test
  - docker-compose -f docker-compose.test.yml up --abort-on-container-exit --build integration-test

after_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push linksmart/service-catalog
