language: go

go:
  - 1.12.x

script:
  - docker-compose -f docker-compose.test.yml up --abort-on-container-exit --build unit-test
  - docker-compose -f docker-compose.test.yml up --abort-on-container-exit --build integration-test

after_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push linksmart/service-catalog

env:
  global:
  - secure: I5OyqXyQodUmll+D+lrQF6NQO9QEndtBcbGe1GBm3CYtnAI0NxCgkkgu/Wb7htlbME5RdNc00Av9d2rfYX1Ga/fqbqglsx/BREgSRAHj8gtORvRxNH/QSU6YtfwCsLrZiEY4GHa6gKmrC6X2YceEzYjyMnap9om47TAZOnTJxGAkO3IaJI3j8weQ9mKCY/Oomxq4GouSivcjMk6RfrBlrQ9eKeCXrPTA99DWLkWWnkhtfyo4Y8q//4zjGBbXWUeqdwQTmEx3lUeiDFLmFmm2okOitN30tu6eWmwtTGFlU9q0rGr7kFtx/DWRhiq2aK1DZNv6UB0H6b4Si8S+EaTNfRMH3M/RWdOrNuq6RPAc3X6LeK1dAaGD/fn5i4QURm5fh2rFZ7fxhQIFcLcrlSYUwMkT7MEbyYWACtZBFVuiHXY6pSCimxlkGBKR2HkmwOlYZyFBCl7eSWEZr0T31EIY+kEZU7VXUy5XXjdfmj0J8wagPcp+VXr3Az7wB5dBRXf7yxF5a7zGu7+dfILoTKW484v3Sgx02h9EPUKU0WrqBgQbmCIBDeuqimS4g1zGl9ZEF2l5pPZco7WfyapXufXYaWQzNFVvuzAPuvBByxsBoEdNuxQb34WSsWLX22iB6+2Vt6ehIX1l7H9yLCOvEMNOIFZTEigiv6pf+T4B8HfjWUc=
  - secure: FM5GOrzR0C51mndm35FS1yibPNJBkS1EULq7j4VcJ1Ry2JXYGaJWxGPS/PzXGWep2U1VopD99XGHzk2Ezkwuo3ebHt3yM14wjM7LavmQwaDF5tr2ITQ517tAeyP+LVAeYkAkTVyKxNPPblkiNlPVDFZfKKI1+9AuCKC4v1NSrMGFfyK0ZYxB9bLEgzqUcbMk1lxIaK3eHTfcLwKbgL901ya0ux5WCLLILbkKDuEG4sogGOB+dBiJ84dJEn9w+hql2xT3ALSufMHielwYcyTJ2QsYQad/guC4H/24vYQDBypHTlDkCYighv+82Lw/o7uiOuPOnA7JWw+zE7r6SZGW/ieR27K5JdUR8W1VyEYaiizYV0Tm86TEB/6Qf5qWz9FpGRBjWpJqgZAEh27MCpFvMFJKlM87A366QasZXWyh+YXkZ6nfJ8EQp/QNZA6uI0NR7NukUlbpZb3dK/KVryHr1n+HJvF8PG/CFzkpuQd/OAZO/1l/Y4FKg86pLcGprQ6Vcpq3OerbYLSo0pwKsP0m0prG0R4K7QYvGnm617LvSYC88tIVxd56Qnvo4NHo2HEjTUWWM9jeZULjKKBoI3MaDKc68lMWdW1BKp/OoMTpgRRnPHoVkew79fNumh0/7PFRGN5pcFZZXPZ5/Wc6LrEXPpoEBDOg+uerjnVBmJVZVfk=
