language: minimal

before_script:
  - export VERSION=${TRAVIS_BRANCH}  BUILDNUM=${TRAVIS_BUILD_NUMBER}
script:
  - docker-compose -f docker-compose.test.yml up --abort-on-container-exit --build unit-test
  - docker-compose -f docker-compose.test.yml up --abort-on-container-exit --build integration-test

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
  - provider: script
    script: docker push linksmart/sc:latest
    on:
      branch: master
  - provider: script
    script: docker tag linksmart/sc linksmart/sc:${TRAVIS_TAG} &&
      docker push linksmart/sc:${TRAVIS_TAG}
    on:
      tags: true

